navsat_transform_node:
  ros__parameters:
    frequency: 5.0
    delay: 3.0

    magnetic_declination_radians: 0.0
    yaw_offset: 0.0

    zero_altitude: true
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame: true

    publish_filtered_gps: true

    use_odometry_yaw: false

    wait_for_datum: false
    datum: [37.5665, 126.9780, 0.0]
