/detect_node:
  ros__parameters:
    image_topic: "/image_raw"
    model_params:
      model: "yolov8.rknn"
      img_size: 640
      conf: 0.5  # Confidence threshold
      iou: 0.8   # IOU threshold
      enable: True

/visualize_node:
  ros__parameters:
    image_topic: "/image_raw"
    detections_topic: "/detections"
    preview: True