usb_cam_node_exe:
  ros__parameters:
    video_device: /dev/videoRGBCAMERA0
    framerate: 30.0
    io_method: mmap
    frame_id: camera_link
    pixel_format: mjpeg2rgb
    av_device_format: YUV422P
    image_width: 640
    image_height: 480
    camera_name: camera
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
    brightness: -1 # 0-255, -1 "leave alone"
    contrast: -1 # 0-255, -1 "leave alone"
    saturation: -1 # 0-255, -1 "leave alone"
    sharpness: -1 # 0-255, -1 "leave alone"
    gain: -1 # 0-100, -1 "leave alone"
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: true
    focus: -1 # 0-255, -1 "leave alone"
