ntrip_client:
  ros__parameters:
    host: "RTS2.ngii.go.kr" # 국토지리정보원 NTRIP
    # host: "192.168." # 사설 NTRIP 기지국
    mountpoint: "VRS-RTCM31"
    username: "" # 계정 아이디
    password: "" # 계정 패스워드

    namespace: ""
    node_name: "ntrip_client"
    debug: false

    port: 2101
    ntrip_version: "None"
    authenticate: true
    ssl: false
    cert: "None"
    key: "None"
    ca_cert: "None"
    rtcm_message_package: "rtcm_msgs"

    rtcm_frame_id: "odom"
    nmea_max_length: 128
    nmea_min_length: 3
    reconnect_attempt_max: 10
    reconnect_attempt_wait_seconds: 5
    rtcm_timeout_seconds: 4
